### ISSUE TITLE
There seems to be some rl4j example code in the rl4j repository.

### ISSUE THREAD

**Issue by AltASoftware** [deeplearning4j/rl4j#10]
https://github.com/deeplearning4j/rl4j/tree/84d78c096b6e127a00644f0b10f9bdce5392c41d/rl4j-core/src/main/java/org/deeplearning4j/rl4j/mdp/toy

Does this code belong in rl4j? It is used from the rl4j examples. But it seems out of place.

**Comment by rubenfiszel** [comment]
No, it's simply mdp defined here for debug purposes so that you don't need any extension (like gym or doom) to test your algorithms. It could be defined in a rl4j-toy submodule but that would be a bit overkill.
