### ISSUE TITLE
More comprehensive documentation on how to implement own MDP

### ISSUE THREAD

**Issue by dan-lind** [deeplearning4j/rl4j#14]
Was discussing with Adam on gitter, and he asked me to post my thoughts here.

The integration with Open AI is great, and I didn't have much trouble getting the cart pole example to run. However I would like to see some more detailed documentation on how to implement your own MDP. The only thing that I can find today is the SimpleToy and HardDeterministicToy classes that are very sparsly documented. 

Would be great if there was some more tangible examples, perhaps something like the grid world described here https://people.eecs.berkeley.edu/~pabbeel/cs287-fa09/lecture-notes/lecture11-6pp.pdf

Could be something simpler as well, but not as simple as SimpleToy which always gives a reward.

**Comment by Zomis** [comment]
Just recently found this repo and couldn't agree more. Doom seems quite heavy to start with and I'd also like to see an example like Grid World.

**Comment by soblenes32** [comment]
+1
Is there a good channel anywhere to get help with the rl4j API?

**Comment by tomthetrainer** [comment]
Our chat channel here, should be were you ask questions
https://gitter.im/deeplearning4j/deeplearning4j

**Comment by Zomis** [comment]
@tomthetrainer And how many questions until a better documentation is made? A public documentation is in my opinion preferable, instead of handling each question that arises in a chat.

**Comment by tomthetrainer** [comment]
@Zomis 

You are welcome to submit documentation as part of these tickets. 

The more you help us to quickly produce the documentation the quicker it is produced.

**Comment by Zomis** [comment]
If I understood things better, gladly. I think you - or pretty much anyone who is a regular in the project - are much more qualified to write the documentation though, which is why I disagree with closing this issue.

To me it seems a bit weird to ask the people who is asking for documentation to write the documentation.
