### ISSUE TITLE
Broken A3C model saving

### ISSUE THREAD

**Issue by ecthx** [deeplearning4j/rl4j#16]
It seems that it is not possible to save trained a3c model. Save method in ACPolicy is commented out.
[https://github.com/deeplearning4j/rl4j/blob/1523002dd08d3ad693652ad1681adc26c4efef5c/rl4j-core/src/main/java/org/deeplearning4j/rl4j/policy/ACPolicy.java#L40-L42](url)

[https://github.com/deeplearning4j/rl4j/blob/1523002dd08d3ad693652ad1681adc26c4efef5c/rl4j-core/src/main/java/org/deeplearning4j/rl4j/network/ac/ActorCriticSeparate.java#L65-L71](url)

It would also be very beneficial if it was possible to save model during training and not only at the end of the training.

**Comment by ecthx** [comment]
Save methods are implemented in ActorCriticCompGraph but I dont see a load method...
[https://github.com/deeplearning4j/rl4j/blob/1523002dd08d3ad693652ad1681adc26c4efef5c/rl4j-core/src/main/java/org/deeplearning4j/rl4j/network/ac/ActorCriticCompGraph.java#L55-L69](url)

Everything seems fine with DQN.

[https://github.com/deeplearning4j/rl4j/blob/1523002dd08d3ad693652ad1681adc26c4efef5c/rl4j-core/src/main/java/org/deeplearning4j/rl4j/network/dqn/DQN.java#L24-L31](url)

[https://github.com/deeplearning4j/rl4j/blob/1523002dd08d3ad693652ad1681adc26c4efef5c/rl4j-core/src/main/java/org/deeplearning4j/rl4j/network/dqn/DQN.java#L75-L88](url)

**Comment by saudet** [comment]
Fixed in the last commit: https://github.com/deeplearning4j/rl4j/commit/6ee3cf01cc9d36c1c446d0534ebac5e2cd424022
