### ISSUE TITLE
Broken with Vizdoom 1.1 api

### ISSUE THREAD

**Issue by Tostino** [deeplearning4j/rl4j#17]
Hey there, I wanted to try my hand at training an AI to play Doom, so I was trying to use this project.

I couldn't find the version of the binary files used in this repo for Vizdoom, so I went about updating it to the 1.1 api that is currently on their site.  

It currently has an issue where it trys to call getCurrentScreen(), and that doesn't exist any more.  Instead you need to call getState().screenBuffer.

That also returns a byte array rather than a int array, so the MdpGameScreen class needs to be changed to accept a byte array in the constructor. Works fine other than that.

**Comment by saudet** [comment]
Fixed in this commit: https://github.com/deeplearning4j/rl4j/commit/d4231669f6be7562de41cc29cc9b414c2183a8f7
