### ISSUE TITLE
Add the ability to plug in iteration listeners in to the api here.

### ISSUE THREAD

**Issue by agibsonccc** [deeplearning4j/rl4j#18]
https://github.com/deeplearning4j/rl4j/blob/master/rl4j-core/src/main/java/org/deeplearning4j/rl4j/network/NeuralNet.java

This would be good for accessing visualizations.

**Comment by saudet** [comment]
Added in https://github.com/deeplearning4j/rl4j/commit/0c0fcb5b610bdac782cd59d8f74855440e896d33
