### ISSUE TITLE
Dependencies not able to found even added sonatype snapshots repository

### ISSUE THREAD

**Issue by JamesLuoau** [deeplearning4j/rl4j#2]
mvn install will have below issue: 

Failed to execute goal on project rl4j-core: Could not resolve dependencies for project org.deeplearning4j.rl4j:rl4j-core:jar:0.5.0-SNAPSHOT: The following artifacts could not be resolved: org.deeplearning4j:deeplearning4j-core:jar:0.5.1-SNAPSHOT, org.nd4j:nd4j-native:jar:0.5.1-SNAPSHOT: Could not find artifact org.deeplearning4j:deeplearning4j-core:jar:0.5.1-SNAPSHOT in ossrh (https://oss.sonatype.org/content/repositories/snapshots) 

I can see there are two ways to fix it:
1) please install the SNAPSHOT version into sonatype
2) download source code of nd4j and deeplearning4j, install into local machine

**Comment by raver119** [comment]
Right now only option nr.2 is viable.

**Comment by JamesLuoau** [comment]
Personally tried option 2 above in my MacBook Pro, works very well. Thank you guys.
