### ISSUE TITLE
Lack of example to demonstrate QLearningDiscreteConv

### ISSUE THREAD

**Issue by agibsonccc** [deeplearning4j/rl4j#27]
https://github.com/deeplearning4j/deeplearning4j/issues/3039

**Comment by howard-abrams** [comment]
Not sure how long you want to wait for this, but I have a Malmo example working that I'll update in PR https://github.com/deeplearning4j/rl4j/pull/21 in a day or so. Then, we'd be waiting for it to get merged (which is waiting on Malmo in maven central), and for issue https://github.com/deeplearning4j/rl4j/issues/30 so it will work properly.

**Comment by saudet** [comment]
We now have ALE: 
https://github.com/deeplearning4j/dl4j-examples/blob/sa_rl4j/rl4j-examples/src/main/java/org/deeplearning4j/examples/rl4j/ALE.java
