### ISSUE TITLE
HistoryProcessor width and height switched

### ISSUE THREAD

**Issue by howard-abrams** [deeplearning4j/rl4j#30]
In the current codebase (0.8-snapshot), the transform method of org.deeplearning4j.rl4j.learning.HistoryProcessor seems to have swapped rescaled width and height when resizing:

```
        Mat resized = new Mat(conf.getRescaledHeight(), conf.getRescaledWidth(), CV_8UC(1));
        resize(cvmat, resized, new Size(conf.getRescaledHeight(), conf.getRescaledWidth()));
```

I suspect that either people have worked around this by swapping those values in the history processor configuration (which I can confirm does work), or simply haven't notices because they were using square images.

**Comment by saudet** [comment]
Good find, please send a PR and I'll merge it!

**Comment by howard-abrams** [comment]
Thanks for the quick reply.  Done.

**Comment by howard-abrams** [comment]
wait - I may have messed up and it's actually the cropping dimensions that are backwards. Give me some time to confirm and get back to you.

**Comment by howard-abrams** [comment]
Ok, sorry about that, now I'm fairly certain it is correct (but please double check - it gets confusing with all the swaps :( ).

Once I swapped the resize, I needed to swap the final reshape. The history processor config is now sane - with x and y's matching between resize and crop.
