### ISSUE TITLE
Javadoc not Available for rl4j

### ISSUE THREAD

**Issue by grayhaired** [deeplearning4j/rl4j#33]
#### Issue Description

Javadoc is not available online for rl4j. It would be great if you could create it and make it online. It would also be great if you add more information about important methods in interfaces/classes. Ex:
StepReply<O> step(A action) in MDP. A new user finds it difficult to understand what exactly it means.

**Comment by crockpotveggies** [comment]
I'll get this done within the day.

**Comment by crockpotveggies** [comment]
You can now find it here for v0.8.0: https://deeplearning4j.org/rl4jdoc/index.html
