### ISSUE TITLE
DiscreteConv + LSTM

### ISSUE THREAD

**Issue by ecthx** [deeplearning4j/rl4j#43]
Many RL implementations have an option to use LSTM network. It would be great if there was an example of how to do that with rl4j.

**Comment by saudet** [comment]
We should be able to create factory classes pretty easily for that. Try to
extend this, for example:
https://github.com/deeplearning4j/rl4j/blob/master/rl4j-core/src/main/java/org/deeplearning4j/rl4j/network/dqn/DQNFactoryStdConv.java

**Comment by saudet** [comment]
Done for A3C in commit https://github.com/deeplearning4j/rl4j/commit/a171fbba7b8891937872709cf80f2b009fee69e3, enjoy!

**Comment by ramsestom** [comment]
I have tried using a LSTM with the Sync QLearning method by creating my own factory class but it fails during the training phase in the setTarget(ArrayList<Transition<Integer>> transitions) at the line `q += targetDqnOutputNext.getDouble(i, getMaxAction.getInt(i));` with the following error:
```
java.lang.IllegalArgumentException: Indexes must be same length as array rank
	at org.nd4j.linalg.api.shape.Shape.getOffset(Shape.java:398)
	at org.nd4j.linalg.api.shape.Shape.getDouble(Shape.java:262)
	at org.nd4j.linalg.api.ndarray.BaseNDArray.getDouble(BaseNDArray.java:1756)
	at org.nd4j.linalg.api.ndarray.BaseNDArray.getDouble(BaseNDArray.java:3660)
	at model.ModelQLearning.setTarget(ModelQLearning.java:231)
```
So it looks like it is not that easy as just creating your own factory class...

**Comment by saudet** [comment]
@ramsestom Have you tried the "useLSTM" configuration?

**Comment by ramsestom** [comment]
No. Where is it?

**Comment by saudet** [comment]
https://github.com/deeplearning4j/rl4j/search?utf8=%E2%9C%93&q=useLSTM&type=

BTW, AFAIK, DQN doesn't support LSTM, or would you have a method to propose?

**Comment by ramsestom** [comment]
Don't know. I am trying to have an implementation similar to this: https://github.com/danielzak/sl-quant/blob/master/ex3-self_learning_quant.py with rl4j. I want to predict some actions based on time series data using reinforcement learning but I don't know what BTW, AFAIK, and DQN are to be honnest.

**Comment by saudet** [comment]
Doesn't look like Deep Q Learning, you'll probably need to implement the algorithm at a lower level than this...

**Comment by ramsestom** [comment]
what I am trying to implement seems to be called DRQN ( Deep Recurrent Q-Networks) https://medium.com/emergent-future/simple-reinforcement-learning-with-tensorflow-part-6-partial-observability-and-deep-recurrent-q-68463e9aeefc
