### ISSUE TITLE
Having trouble with new load() in IActorCritic

### ISSUE THREAD

**Issue by ecthx** [deeplearning4j/rl4j#44]
Sorry for not providing more info but Im on my mobile now. It seems that rl4j is complaining about rd being null. It would be great if there was an example on how to use trained a3c model. When I get home I will update this issue.

**Comment by saudet** [comment]
I've added tests here and they work fine:
https://github.com/deeplearning4j/rl4j/commit/a6949d5e1cfc6bf1265b11cfc6cfcd69f5fbb92a
Please provide more details, thanks!

Working on A3C right now, should get more updates soon...

**Comment by ecthx** [comment]
It would be great to have an example on how to use this i dl4j-examples.
Something similar to [https://github.com/deeplearning4j/dl4j-examples/blob/master/rl4j-examples/src/main/java/org/deeplearning4j/examples/rl4j/Cartpole.java#L83](url)
But for A3Cartpole
Thanks

**Comment by saudet** [comment]
I've started to put updated examples in a branch of dl4j-examples, the A3CCartpole one among others:
https://github.com/deeplearning4j/dl4j-examples/blob/sa_rl4j/rl4j-examples/src/main/java/org/deeplearning4j/examples/rl4j/A3CCartpole.java
