### ISSUE TITLE
Workspaces

### ISSUE THREAD

**Issue by ecthx** [deeplearning4j/rl4j#45]
I'm probably doing something wrong but when I try to enable workspaces I'm getting flooded with messages like this in the console output:
o.d.n.m.MultiLayerNetwork - Starting MultiLayerNetwork with WorkspaceModes set to [training: SINGLE; inference: SINGLE]
I can quiet them down by turning log lever to ERROR but then other useful info disappears.

**Comment by saudet** [comment]
We can turn off the log for that. But this happens because the model is
constantly cloned, which is not very efficient anyway, so that needs to be
fixed. As usual though, contributions are welcome!

**Comment by saudet** [comment]
Fixed in commit https://github.com/deeplearning4j/rl4j/commit/c78a63351718d4eab08a19ad9ca37334268dc33b
