### ISSUE TITLE
How to enable UI?

### ISSUE THREAD

**Issue by ecthx** [deeplearning4j/rl4j#48]
I can't figure out how to enable UI in my project.
Simple example would help a lot.

Thanks for great work

**Comment by tomthetrainer** [comment]
Please download our examples repo,

https://github.com/deeplearning4j/dl4j-examples

There are UI examples there, 

https://github.com/deeplearning4j/dl4j-examples/tree/master/dl4j-examples/src/main/java/org/deeplearning4j/examples/userInterface

Also our web page has some documentation
https://deeplearning4j.org/visualization

**Comment by ecthx** [comment]
Yes I know about the examples repository but it seems to me that typical UI example does not
easily translate to rl4j.

**Comment by saudet** [comment]
We just need to set an IterationListener in the config: https://github.com/deeplearning4j/rl4j/commit/0c0fcb5b610bdac782cd59d8f74855440e896d33
What happens when you do that?

**Comment by ecthx** [comment]
So I tried to modify A3CCartpole and set my listener in ActorCriticFactorySeparateStdDense.Configuration like this:
                        3, //num layer
                        30,   //hidden nodes
                        1e-2,
                        .00000,
                        null,
                        new IterationListener[] {new StatsListener(storage, 1)}

I get this info in the log:
o.d.u.p.PlayUIServer - StatsStorage instance attached to UI: InMemoryStatsStorage(uid=8fcd6115)
But UI webpage does not update.
When I try FileStatsStorage it creates two files but their size stays constant as the training progresses.
Sorry for crappy formatting.

**Comment by saudet** [comment]
@ecthx Fixed in https://github.com/deeplearning4j/rl4j/commit/793f123e373301e423289acd10ae376002e20e5e
