### ISSUE TITLE
Learning not as good as one example

### ISSUE THREAD

**Issue by rubenfiszel** [deeplearning4j/rl4j#5]
https://gym.openai.com/evaluations/eval_TqZof2RFQnGin4l5na0sA

This seems to be much more efficient than what rl4j achieve on Cartpole. The curve progress starts much earlier. Find out why (Implementation issue?).

**Comment by gowthamnatarajan** [comment]
Is this fixed with the release few days after this bug was filled? Or was this not an issue?

**Comment by rubenfiszel** [comment]
Yes, this was fixed by normalization. Thank you for remembering me to close it.
