### ISSUE TITLE
Somethings not right (or has changed) with history processor / pixels

### ISSUE THREAD

**Issue by howard-abrams** [deeplearning4j/rl4j#56]
A few months back, I had a working, pixel-based, rl4j sample app that converged fairly quickly. After merging in many changes to rl4j over the past few months, it no longer works using the most recent code from' master'.

From what little I've been able to determine, I _think_ the issue _may_ be related to https://github.com/deeplearning4j/rl4j/commit/d4231669f6be7562de41cc29cc9b414c2183a8f7. Part of that commit was to change the fmpeg frame recording in the history processor to expect normalized pixels: `ocvmat.convertTo(cvmat, CV_8UC(3), 255.0, 0.0);`

That was not how it worked before, and it seems to conflict with the 'transform' function in the history processor where it does not expect normalized pixels.  

Not sure where this leaves me: 
1. Have other places in the code been changed to expect normalized pixels and 'transform' is out of date? In which case, how is vizdoom functioning and what does UINT8 compression of that matrix do if all the values are 0.0-1.0?

-or-

2. Are the pixel _not_ suppose to be normalized and just that one line in 'record' is a mistake? If so, how does vizdoom function? and then what else could have changed to cause my sample to stop working?

**Comment by saudet** [comment]
Normalization is expected to happen in the MDP yes, like it was updated in VizDoom for example:
https://github.com/deeplearning4j/rl4j/commit/d4231669f6be7562de41cc29cc9b414c2183a8f7#diff-51a80d538994d44779d01c52ceaad156

Previously, it was hard coded to assume that anything would be [0, 256] and it would do it in concat() only:
https://github.com/deeplearning4j/rl4j/commit/63adcf02980cf8baea395adf1bb333ec0ed57c21#diff-0e254479821c42bc291337248dd9b58d

**Comment by saudet** [comment]
Could you point me to any other places where it expects to transform unnormalized data?

**Comment by howard-abrams** [comment]
Thanks for the reply.  I wasn't aware of that 1/256 in concat, and it makes sense that it was removed. 

But something's still not right on my end.  The part where I was saying that transform is expecting non-normalized data is in HistoryProcessor.transform(INDArray raw):
``` 
Mat ocvmat = new Mat(shape[0], shape[1], CV_32FC(3), raw.data().pointer());
Mat cvmat = new Mat(shape[0], shape[1], CV_8UC(3));
ocvmat.convertTo(cvmat, CV_8UC(3));

This was working prior to normalization - it I do an `imwrite` of cvmat at this point with normalized data, I get a black image. If I don't normalize the observed pixels, it get the full color image I'd expect.  From what I've read online, opencv's CV_32F is expecting 0.0-1.0, so I would have expected the opposite results but that appears not to be the case because "record" is now denormalizing the data before writing it to the mpeg.

Why shouldn't transform also be denormalizing the data when converting to CV_8UC like in record?

**Comment by saudet** [comment]
Ah, I see, thanks for reporting this! I forgot to update this method. We really need to start making better unit tests for all that :) Fixed this latest commit https://github.com/deeplearning4j/rl4j/commit/d7170f64976f66f5b151d8bca663911b530ae66a

**Comment by howard-abrams** [comment]
Thanks, but I'm not sure that's correct.

You're renormalizing the data and then the code attempts to store it un UINT8 when it compresses it. The result is that all the pixels are either 0.0 or 1.0 when the history is used for training. At least that's what I'm seeing - unit tests are exactly what is needed here :)

I can play some more with some options, but interested in your thoughts since you know the code better.

**Comment by howard-abrams** [comment]
Just a quick update:

I ran the updated code and things didn't seem to work well.  I then updated the HistoryProcessor code you checked in, but used Float8 compression instead of UINT8 and it worked. I noticed the docs for Float8 said it wasn't implemented,  but it worked - perhaps it's only implemented in native and not CUDA, etc? Again, I'm a bit out of my element in this codebase, so I'm not sure what ramifications changing that compression type has.

**Comment by saudet** [comment]
Ah, I see, I didn't notice we were compressing it to integers, oops. @raver119 does Float8 work??

**Comment by howard-abrams** [comment]
I should also mention that there seems to be some precision loss using Float8, so even if it's working it might not be the best solution.

**Comment by saudet** [comment]
That was for memory constraints. If your problem is small enough, we don't
need it. We could have a flag? Although for images byte from 0 to 255 is
enough without precision loss...

**Comment by howard-abrams** [comment]
If Float8 DOES work, then I propose we change it to Float8 and add a flag to turn off compression for when people need more that ~7 bits of precision.

**Comment by saudet** [comment]
The problem with Float8 is that even if it works, it doesn't represent well numbers in the [0.0, 1.0] range.

@raver119 Do you think it would be possible to compress with Uint8 in fixed-point? Like with a scale or a shift for cases like this?

**Comment by saudet** [comment]
I've worked around this issue in the latest commit https://github.com/deeplearning4j/rl4j/commit/f515c6bc00dacd442ef9feb523b91b09c8ea3077. It doesn't make sense to have compression as an option because we're not losing any accuracy in the case of images from video games. Though it's always possible to implement a new HistoryProcessor that uses different compression at a different scale, as required by the data we might be processing. In any case, let me know if this works well for your application. Thanks for the feedback!

**Comment by howard-abrams** [comment]
I think this approach makes sense, but it looks like there's a bug in commit https://github.com/deeplearning4j/rl4j/commit/f515c6bc00dacd442ef9feb523b91b09c8ea3077.  

If you look at line 212 in [QLearningDiscrete](https://github.com/deeplearning4j/rl4j/commit/f515c6bc00dacd442ef9feb523b91b09c8ea3077#diff-228375870af85c3a7363e27ee3c76174), the scaling is done within the loop over the memories. That means each memory is scaled multiple times resulting in a whole bunch of zeros (except for the last memory).  I made a local change to move that block of code after the next brace and that seemed to fix things for my sample.

There could be more problems hiding in there, but I didn't see anything more.

**Comment by saudet** [comment]
Ah, yes, thanks for pointing this out. Fixed!

BTW, what is this sample that you are running? Could you send a pull request? I'm looking for a good way to test this thing, but am not having much luck tuning a game from ALE...

**Comment by howard-abrams** [comment]
Looks good.

I've been using my minecraft sample: https://github.com/howard-abrams/dl4j-examples/blob/master/rl4j-examples/src/main/java/org/deeplearning4j/examples/rl4j/MalmoPixels.java

I haven't summited a PR for it yet because I'm waiting for https://github.com/deeplearning4j/rl4j/pull/21 to land first since it has dependencies on that.

**Comment by saudet** [comment]
There, it's merged!

**Comment by howard-abrams** [comment]
Thanks - I'll put together a PR for the samples next.
