### ISSUE TITLE
Accessing MultiLayerNetwork and setListeners method to create UI Server

### ISSUE THREAD

**Issue by grayhaired** [deeplearning4j/rl4j#57]
I'm trying to set up UI Server for RL4j... I couldn't get setListners method for neuralnet I obtained from dql, which is why I tried following method, which is not working...

        QLearningDiscreteDense<MyState> dql = new QLearningDiscreteDense<TourState>(mdp, TOY_NET, TOY_QL, manager);
        UIServer uiServer = UIServer.getInstance();
        StatsStorage statsStorage = new InMemoryStatsStorage();
        uiServer.attach(statsStorage);

        MultiLayerNetwork mln = (MultiLayerNetwork) dql.getNeuralNet();
        mln.setListeners(new StatsListener(statsStorage));

I'm getting java.lang.ClassCastException: exception...

Is there anyway I can get MultiLayerNetwork from dql, so that I can use setListener method?

Just to add some more info, This is very similar to Toy example...

**Comment by saudet** [comment]
Could you try to set that field instead?
https://github.com/deeplearning4j/rl4j/blob/master/rl4j-core/src/main/java/org/deeplearning4j/rl4j/network/dqn/DQNFactoryStdDense.java#L78

**Comment by grayhaired** [comment]
Thanks for reply!

I tried doing this, but all I'm seeing blank visualization board with no graphs...

Field declaration...

        public static IterationListener[] listeners = new ScoreIterationListener[1];
        public static DQNFactoryStdDense.Configuration TOY_NET =    DQNFactoryStdDense.Configuration.builder().l2(0.001).learningRate(0.0005).numLayer(8).numHiddenNodes(61).listeners(listeners).build();

In the implementation, 
  
        QLearningDiscreteDense<MyState> dql = new QLearningDiscreteDense<TourState>(mdp, TOY_NET, TOY_QL, manager);
        UIServer uiServer = UIServer.getInstance();
        StatsStorage statsStorage = new InMemoryStatsStorage();
        uiServer.attach(statsStorage);

   Please let me know what I'm missing. Thanks!

**Comment by saudet** [comment]
You'll need to add some listeners to that array...

**Comment by grayhaired** [comment]
Yes, I also thought that, and implemented this -- 

      public static IterationListener[] listeners = new StatsListener[]{new StatsListener(new InMemoryStatsStorage())};

       public static DQNFactoryStdDense.Configuration TOY_NET =
            DQNFactoryStdDense.Configuration.builder()
             .l2(0.001).learningRate(0.0005).numLayer(8).numHiddenNodes(61).listeners(listeners).build();


Still no results,, I'm not even able to see anything in model or system section of UI board...

**Comment by grayhaired** [comment]
I think I resolved it... By modifying the source code and building it locally. 
I had to edit DQN and IDQN in network.

In IDQN, which is an interface - 
Add these:

      public void setListeners(IterationListener... listeners);
      public void setListeners(Collection<IterationListener> listeners);

Implement them in DQN like this:

        public void setListeners(IterationListener... listeners) {
          mln.setListeners(listeners);
        }

        public void setListeners(Collection<IterationListener> listeners) {
          mln.setListeners(listeners);
        }

Then I built locally. Works like charm. I got all the graphs and models.  You could update this in the next release....

**Comment by saudet** [comment]
Specifying them in the config does exactly the same thing though...

**Comment by saudet** [comment]
I've just tried here and this works fine:
```java
    UIServer uiServer = UIServer.getInstance();
    StatsStorage statsStorage = new InMemoryStatsStorage();
    uiServer.attach(statsStorage);
    IterationListener[] listeners = new StatsListener[]{new StatsListener(statsStorage)};

    DQNFactoryStdDense.Configuration TOY_NET2 =
            DQNFactoryStdDense.Configuration.builder()
                    .listeners(listeners)
                    .learningRate(0.0005)
                    .l2(0.001)
                    .numHiddenNodes(16)
                    .numLayer(3).build();

   dql = new QLearningDiscreteDense<SimpleToyState>(mdp, TOY_NET2, TOY_QL, manager);
```

But, it's a bit convoluted I agree. We'll probably be adding some getters for the underlying networks.

**Comment by grayhaired** [comment]
Thanks for the code. This worked for me too! Looking forward for getters for network. That would enable many other things....

**Comment by saudet** [comment]
Fixed in commit https://github.com/deeplearning4j/rl4j/commit/0da3ded3e2742b977a3ee8df2c764fe00a2a6064. Thanks for the feedback! 

/cc @ecthx
