### ISSUE TITLE
We do not have characteristic  Graphs for Reinforcement learning

### ISSUE THREAD

**Issue by grayhaired** [deeplearning4j/rl4j#62]
#### Issue Description
While we have great visualization and graphs for all kinds of neural networks, for reinforcement learning we do not have graphs that will help us very much in understanding and debugging. 

- expected behavior
Graphs for following
  reward vs epoch (or iteration)
  Q vs epoch (or iteration)
  reward vs step
  Q vs step 
  Cumulative rewards vs steps
  Cumulative rewards vs epoch (or iteration)

- encountered behavior
   We have graph available only on scala webapp, but in need in regular rl4j.

**Comment by saudet** [comment]
Scala version of rl4j? Where?

@rubenfiszel started working on something (https://github.com/rubenfiszel/webapp-rl4j), with a bit of work we could integrate that to this.

**Comment by grayhaired** [comment]
Apologies. I just wanted to point out to same scala webapp. Thanks for accepting this enhancement.

**Comment by saudet** [comment]
We can continue developing that webapp in Scala, as another submodule of rl4j proper, that would be fine!

**Comment by AlexDBlack** [comment]
This issue was moved to deeplearning4j/deeplearning4j#5265
