### ISSUE TITLE
save and load function (moved from dl4j-examples)

### ISSUE THREAD

**Issue by RobAltena** [deeplearning4j/rl4j#66]
moving from https://github.com/deeplearning4j/dl4j-examples/issues/443

> I have see the play function of a DQNPolicy in tl4j do not work with a MDP<MyState, Integer, DiscreteSpace> argument
I do not know why, because it is that is shown in the hardtoy
>
>Another problem is when I load a policy, it is impossible to continue to learn. Why we can just serialize the policy ? It will be simpler if we can serialize DataManager, QLearningDiscreteDense and MDP to continue to learn when we have new data.
>
>It can be a big serialization but it is very useful I think

**Comment by saudet** [comment]
What do you mean by DQNPolicy.play() not working? What error do you get?

**Comment by Ceubex** [comment]
I just need to serialize the policy but it is not possible

**Comment by saudet** [comment]
DQNPolicy.save() works just fine:
https://github.com/deeplearning4j/dl4j-examples/blob/master/rl4j-examples/src/main/java/org/deeplearning4j/examples/rl4j/Cartpole.java#L72

And we can reload it into a Learning object as explained in issue #71.

**Comment by saudet** [comment]
Marking as duplicate of #71
