### ISSUE TITLE
Cannot get DQN from policy

### ISSUE THREAD

**Issue by schrum2** [deeplearning4j/rl4j#69]
In this file, https://github.com/deeplearning4j/rl4j/blob/273564b2e35294a83893688b9033013fe24129b6/rl4j-core/src/main/java/org/deeplearning4j/rl4j/policy/DQNPolicy.java , why is getNeuralNet() protected? After loading a policy from a saved file, I need access to the DQN in order to train it further.

**Comment by saudet** [comment]
Fixed in latest commit https://github.com/deeplearning4j/rl4j/commit/8373fd3d5e9bb1d9c883c4ea2e071a34bba11b6f . Thanks for reporting!

**Comment by schrum2** [comment]
So, obviously, I could work from the source and have this change in my code immediately. However, I'm primarily using my POM to import the latest dependencies through Maven ... when will I be able to get this change through Maven, and what would the version number be?

**Comment by ecthx** [comment]
You would have to enable snapshots in your POM and then use 0.9.2-SNAPSHOT as a version.
Problem is that snapshots are currently broken and last one was generated more than a month ago.
[https://oss.sonatype.org/content/repositories/snapshots/org/deeplearning4j/rl4j/0.9.2-SNAPSHOT/](url)
