### ISSUE TITLE
No way to load a policy into a neural network

### ISSUE THREAD

**Issue by viluon** [deeplearning4j/rl4j#71]
#### Issue Description
`DQNPolicy` has means of serialising and unserialising, but there seems to be no way to load the policy into a `Learning` object. Please excuse my ignorance in case such a way already exists.

#### Contributing
I'm willing to help, but lacking experience with both D/RL4J and Java itself...

**Comment by saudet** [comment]
The DQNPolicy object itself is just a wrapper for IDQN. We can reuse the IDQN from an existing DQNPolicy by passing DQNPolicy.getNeuralNet() to the constructor of QLearningDiscreteDense, etc.

It doesn't look like there's an example demonstrating that anywhere at the moment, so I'll mark this as "enhancement".

**Comment by wutzebaer** [comment]
hm but DQNPolicy.getNeuralNet() is protected

**Comment by wutzebaer** [comment]
I don't know if it is correct but at least it compiles an run:

```
dql.getNeuralNet().save("test.zip");
DQN load = DQN.load("test.zip");
dql = new QLearningDiscreteDense<BwinState>(mdp, load, TOY_QL, manager);
```

**Comment by saudet** [comment]
It isn't anymore: https://github.com/deeplearning4j/rl4j/commit/8373fd3d5e9bb1d9c883c4ea2e071a34bba11b6f

**Comment by wutzebaer** [comment]
ok but it seems that my second code will create the  same result, isnt it?

**Comment by saudet** [comment]
Yes, that's better actually :)

**Comment by AlexDBlack** [comment]
This issue was moved to deeplearning4j/deeplearning4j#5268
