### ISSUE TITLE
Can't build on Mac OS-X

### ISSUE THREAD

**Issue by pokowaka** [deeplearning4j/rl4j#73]
#### Issue Description

Please describe your issue, along with:
- expected behavior'
git clone ...
mvn compile 

should succeed

- encountered behavior
[ERROR] Failed to execute goal on project rl4j-api: Could not resolve dependencies for project org.deeplearning4j:rl4j-api:jar:0.9.2-SNAPSHOT: Failure to find org.nd4j:nd4j-native:jar:macosx-x86_64:0.9.2-SNAPSHOT in https://oss.sonatype.org/content/repositories/snapshots was cached in the local repository, resolution will not be reattempted until the update interval of sonatype-nexus-snapshots has elapsed or updates are forced -> [Help 1]
[ERROR]

#### Version Information

Please indicate relevant versions, including, if relevant:

* platform information (OS, etc)
Sierra (10.12.6)

#### Contributing

I'm trying to clean up some of the interfaces, but can't build.

**Comment by saudet** [comment]
Until the SNAPSHOT artifacts are available, you'll need to build ND4J as well, unfortunately...

**Comment by pokowaka** [comment]
Ok, got that part fixed. Now there is another set of failures:

ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.1:compile (default-compile) on project rl4j-core: Compilation failure: Compilation failure:
[ERROR] /Users/erwinj/src/java/rl4j/rl4j-core/src/main/java/org/deeplearning4j/rl4j/network/dqn/DQN.java:[94,33] cannot find symbol
[ERROR]   symbol:   method getEpochCount()
[ERROR]   location: variable mlnConf of type org.deeplearning4j.nn.conf.MultiLayerConfiguration
[ERROR]
[ERROR] /Users/erwinj/src/java/rl4j/rl4j-core/src/main/java/org/deeplearning4j/rl4j/network/dqn/DQN.java:[95,25] method update in interface org.deeplearning4j.nn.api.Updater cannot be applied to given types;
[ERROR]   required: org.deeplearning4j.nn.api.Layer,org.deeplearning4j.nn.gradient.Gradient,int,int
[ERROR]   found: org.deeplearning4j.nn.multilayer.MultiLayerNetwork,org.deeplearning4j.nn.gradient.Gradient,int,int,int
[ERROR]   reason: actual and formal argument lists differ in length
[ERROR] /Users/erwinj/src/java/rl4j/rl4j-core/src/main/java/org/deeplearning4j/rl4j/network/dqn/DQN.java:[100,25] method iterationDone in interface org.deeplearning4j.optimize.api.IterationListener cannot be applied to given types;

**Comment by raver119** [comment]
Build pipeline should look like this:

libnd4j -> nd4j -> DataVec -> deeplearning4j -> rl4j

Can you confirm you’ve followed it? Right now it looks like you’ve skipped deeplearning4j step at least

**Comment by pokowaka** [comment]
ok. Let me give it a try, thnx!

**Comment by pokowaka** [comment]
That fixed it!
