### ISSUE TITLE
Remove dependency on gym-env

### ISSUE THREAD

**Issue by pokowaka** [deeplearning4j/rl4j#74]
This is more of a suggestion.

I noticed that the rl4j libraries depend on gym-env for the following:

./src/main/java/org/deeplearning4j/gym/StepReply.java
./src/main/java/org/deeplearning4j/rl4j
./src/main/java/org/deeplearning4j/rl4j/space
./src/main/java/org/deeplearning4j/rl4j/space/ActionSpace.java
./src/main/java/org/deeplearning4j/rl4j/space/ArrayObservationSpace.java
./src/main/java/org/deeplearning4j/rl4j/space/DiscreteSpace.java
./src/main/java/org/deeplearning4j/rl4j/space/Encodable.java
./src/main/java/org/deeplearning4j/rl4j/space/HighLowDiscrete.java
./src/main/java/org/deeplearning4j/rl4j/space/ObservationSpace.java

It seems that these classes should belong to rl4j vs gym-env. Some arguments in favor of moving them to rl4j repo:

- One fewer dependency, no need to bring in GymEnv if you are Qlearning without it
- All the code in one repo, this makes it easier to maintain and see what is happening where. 
- Generation of Javadoc would be self contained as well. 

On a side note
- StepReply has a jsonobject which is unused.
- StepReply package name is odd from QLearn perspective.

Let me know if you think this would be an idea worth pursuing, I can create a pull request

**Comment by saudet** [comment]
See discussion at #58
