### ISSUE TITLE
RL4J not supported on Windows

### ISSUE THREAD

**Issue by AltASoftware** [deeplearning4j/rl4j#8]
RL4J builds a client to the OpenAI gym through their http api.
https://github.com/openai/gym-http-api

The problem is that OpenAI Gym does not support windows.  (https://github.com/openai/gym ) As a result RL4J will have a hard time on Windows.

**Comment by rubenfiszel** [comment]
You only need to implement an MDP to use RL4j. You don't need to use gym.

**Comment by AltASoftware** [comment]
In the [quickstart](https://github.com/deeplearning4j/rl4j#quicktry-cartpole) it says for step 2:
•launch http api server.

Maybe I wrongly assumed this to be the OpenAI http server? It did not run well on Windows. Reading through the OpenAI repositories I found that the gym only supports Linux and iOS.

Can you provide an example, no matter how simple, of an MDP without using gym?

**Comment by rubenfiszel** [comment]
Gym is just a collection of mdp.
Toy in rl4j is an example of mdp that doesn't require gym.
There is an usage example in rl4j-examples

Ruben Fiszel

2016-09-20 2:34 GMT-07:00 Robert Altena <notifications@github.com>:

**Comment by AltASoftware** [comment]
Thank you for the quick reply. Appreciated.
 I will have a look at Toy.  (Next week.)
