### ISSUE TITLE
Document the QLConfiguration parametters

### ISSUE THREAD

**Issue by ramsestom** [deeplearning4j/rl4j#82]
Please clearly document the various QLConfiguration parametters. 
For now, comments in examples just give a rough idea of what they are like:
>                     123,      //Random seed
>                     10000,    //Max step By epoch
>                     8000000,  //Max step
>                     1000000,  //Max size of experience replay
>                     32,       //size of batches
>                     10000,    //target update (hard)
>                     500,      //num step noop warmup
>                     0.1,      //reward scaling
>                     0.99,     //gamma
>                     100.0,    //td-error clipping
>                     0.1f,     //min epsilon
>                     100000,   //num step for eps greedy anneal
>                     true      //double-dqn
but it is really insufficient.
Some are common to the dl4j neural networks configuration (https://deeplearning4j.org/troubleshootingneuralnets) but most are specific to rl4j and without a clear documentation of what they are acting on and what is their role, it is difficult to tune them for our own case...

**Comment by AlexDBlack** [comment]
https://github.com/deeplearning4j/deeplearning4j/issues/5269
