### ISSUE TITLE
Bug with action selection?

### ISSUE THREAD

**Issue by ramsestom** [deeplearning4j/rl4j#84]
I am trying to use my own MDP with, at each state, an ActionSpace that is only a subset of all the possible actions (I have 3 possibles actions that are defined with Integers: 0, 1 and 2 but, at each step, actions 1 and/or 2 might not be possible). 
The problem is that when I train my model, the step(Integer action) function is sometimes called without getActionSpace() beeing called first. In that the QLearningDiscreteDense algortihm seems to always take the action "1" (from what I have seen in my log output). 
It seems like a bug to me.

Here is my how I traced the issue.

In my MDP class:

 ```
  public OrderActionSpace getActionSpace() {
    	System.out.println("Request action space");
        ...... a function that return the possible actionspace given the current state here
     }

    public StepReply<ModelStateObservation> step(Integer action) 
    {
    	System.out.println("Step with action "+action);
        ... A function that construct the next state here
    }
```

My OrderActionSpace class:

```
public class OrderActionSpace extends DiscreteSpace 
{
    final protected List<Integer> actions;
   
    public OrderActionSpace(List<Integer> actions) {
    	super(actions.size());
    	this.actions= actions;
    }
    public Integer randomAction() {
    	System.out.println("Choose random action from "+actions.stream().map(Object::toString).collect(Collectors.joining(", ")));
        return actions.get(rd.nextInt(actions.size()));
    }

    public Integer noOp() {
        return Constants.ACTION_DO_NOTHING; // Constants.ACTION_DO_NOTHING = 0
    }
    
}
```

And the partial output:

```
Choose random action from 0, 2
Step with action 0
Request action space
Choose random action from 0, 2
Step with action 2
Request action space
Choose random action from 0, 1, 2
Step with action 2
Request action space
Choose random action from 0, 1
Step with action 1
Step with action 1
Request action space
Choose random action from 0, 2
Step with action 0
Step with action 1
Step with action 1
Step with action 1
Step with action 1
Step with action 1
Step with action 1
Step with action 1
Request action space
Choose random action from 0, 2
Step with action 2
Step with action 1
Request action space
Choose random action from 0, 2
Step with action 0
Request action space
Choose random action from 0, 2
Step with action 0
Request action space
Choose random action from 0, 2
Step with action 0
Step with action 1
```

As you can see, there is some "Step with action 1" output that are not dirrectly preceded by a "Choose random action from x..." line. Meaning getActionSpace() from MDP and randomAction() from my action space is not systematically called by QLearningDiscreteDense before a step(Integer action) call...

**Comment by saudet** [comment]
This is working as intended. The action space can't change after initialization. Would you have a different method to propose?
