### ISSUE TITLE
Allow QLearning training to terminate before maxEpochStep when training goal has been achieved

### ISSUE THREAD

**Issue by shanusmcshan** [deeplearning4j/rl4j#87]
Allow the MDP to signal to QLearning that training is complete so that QLearning may terminate before maxEpochStep reached as the training goal has been achieved.

In my case this is when a certain epoch reward has been achieved consistently over a certain number of epochs, however there are certainly other scenarios.

**Comment by AlexDBlack** [comment]
This issue was moved to deeplearning4j/deeplearning4j#5270
