### ISSUE TITLE
Question: are there plans to implement continuous action space?

### ISSUE THREAD

**Issue by Ailanz** [deeplearning4j/rl4j#88]
Hi, I'm loving the framework and I'm just wondering that if there are plans (if so, any estimates) on continuous action spaces? Right now I only see discrete. Thanks!

**Comment by saudet** [comment]
Yes, but that's an area we could use some help in implementing though

**Comment by AlexDBlack** [comment]
This issue was moved to deeplearning4j/deeplearning4j#5271

**Comment by MrStonkus** [comment]
Hi, does this future "continuous action space" is implemented?

**Comment by sergey-rubtsov** [comment]
I tried to implement the continuous on my own, but so far unsuccessfully.
