### ISSUE TITLE
Class not implementiag all methods

### ISSUE THREAD

**Issue by gowthamnatarajan** [deeplearning4j/rl4j#9]
This class https://github.com/deeplearning4j/rl4j/blob/master/rl4j-core/src/main/java/org/deeplearning4j/rl4j/mdp/toy/SimpleToy.java is not implementing all methods of the interface MDP.

**Comment by huitseeker** [comment]
The `@Getter` and `@Setter` annotations show methods implemented [by Lombok](https://projectlombok.org/features/GetterSetter.html). I can't reproduce any compilation errors on  babcf865372b5ed79b3303b2403f3a96ee157607
