### ISSUE TITLE
Weighted Double Q Learning

### ISSUE THREAD

**Issue by tom-adsfund** [deeplearning4j/rl4j#95]
Double Q Learning (greatly) improved on Q Learning to prevent inevitable upward bias.

But DQL has its own (downward) bias issues, which is where WDQL comes in.

Paper: https://www.ijcai.org/proceedings/2017/0483.pdf

Has been used recently in multi agent cooperative reinforcement with success: https://arxiv.org/pdf/1802.08534.pdf

**Comment by AlexDBlack** [comment]
This issue was moved to deeplearning4j/deeplearning4j#5275
